function generatePDF(e) {
    var params = e.parameter; // फॉर्म डेटा
  
    var docTitle = "Leave Application - " + params.employee;
    var logoUrl = "https://your-company-logo-url.com/logo.png"; // अपना लोगो URL डालें
    var companyName = "Virgo® Aluminum Ltd. Ahmedabad, Gujarat";
    
    var htmlTemplate = `
      <html>
        <head>
          <style>
            body { font-family: Arial, sans-serif; text-align: center; padding: 20px; }
            .header { display: flex; align-items: center; justify-content: center; }
            .logo { max-width: 100px; margin-right: 20px; }
            .company-name { font-size: 18px; font-weight: bold; }
            .container { text-align: left; margin-top: 20px; border: 1px solid #000; padding: 10px; }
            .footer { margin-top: 20px; font-size: 12px; }
          </style>
        </head>
        <body>
          <div class="header">
            <img src="${logoUrl}" class="logo"/>
            <div class="company-name">${companyName}</div>
          </div>
          <h2>Leave Application Form</h2>
          <div class="container">
            <p><strong>Employee Name:</strong> ${params.employee}</p>
            <p><strong>Mobile Number:</strong> ${params.mobile}</p>
            <p><strong>Start Date:</strong> ${params.start_date}</p>
            <p><strong>End Date:</strong> ${params.end_date}</p>
            <p><strong>Leave Duration:</strong> ${params.duration} days</p>
            <p><strong>Email:</strong> ${params.email}</p>
            <p><strong>Address:</strong> ${params.address}</p>
            <p><strong>Department:</strong> ${params.department}</p>
            <p><strong>Leave Type:</strong> ${params.type}</p>
            <p><strong>Reason:</strong> ${params.reason}</p>
          </div>
          <div class="footer">This document is auto-generated by Virgo® Aluminum Ltd.</div>
        </body>
      </html>
    `;
  
    var blob = HtmlService.createHtmlOutput(htmlTemplate).getBlob().setName(docTitle + ".pdf").getAs("application/pdf");
    
    var folder = DriveApp.getFolderById("YOUR_GOOGLE_DRIVE_FOLDER_ID"); // 🔹 जहां PDF सेव होगा
    var file = folder.createFile(blob);
    
    var pdfUrl = file.getUrl(); // PDF ka link
    
    // ✅ Google Sheet में PDF लिंक सेव करना
    var sheet = SpreadsheetApp.openById("YOUR_GOOGLE_SHEET_ID").getSheetByName("Sheet1");
    sheet.appendRow([params.employee, params.mobile, params.email, pdfUrl]);
  
    return pdfUrl; // PDF लिंक वापस करें
  }
  